import Config from 'react-native-config';

export const CONFIG = {
  API_URL: Config.API_URL,
  MAP_DEBUG: Config.MAP_DEBUG == 'true',
  GAME_MIN_REQUIRED_EXPERIENCE: Config.GAME_MIN_REQUIRED_EXPERIENCE,
  GAME_EXPERIENCE_FACTOR: Config.GAME_EXPERIENCE_FACTOR,
  PLAYER_REACH_RADIUS: Config.PLAYER_REACH_RADIUS
    ? parseFloat(Config.PLAYER_REACH_RADIUS)
    : 0.008
};
