name: Continuous Integration Checks

on:
  pull_request:
    branches: 
      - main
      - development
    types: [ opened , synchronize , reopened, ready_for_review ]

jobs:
  integration:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Check for linting errors
        run: yarn lint

      - name: Check formatting
        run: yarn format:check

      # Todo: Implement check for tests
